#====================
#Server Configuration
#====================
server:
  port: 1989
spring:
  application:
    name: gateway-service
---
spring:
  output:
    ansi:
      enabled: always
#===========================
#Eureka Client Configuration
#===========================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
---
#=====================
#Gateway Configuration
#=====================
---
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health
  tracing:
    sampling:
      probability: 1.0
---
#====================
#Routes Configuration
#====================
spring:
  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    gateway:
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/v1/students/**
        - id: program-service
          uri: lb://PROGRAM-SERVICE
          predicates:
            - Path=/api/v1/programs/**
            - Path=/api/v1/admissions/requirement




