#=====================
#Service Configuration
#=====================
spring:
  application:
    name: gateway-service
---
#Import configurations from the config service
spring:
  config:
    import: optional:configserver:http://localhost:1987






