name: EduFusion-Hub CI - Build

on:
  pull_request:
    branches:
      - master
      - staging
      - develop

jobs:
  build:
    name: Build and Test eduFusion-Hub
    runs-on: ubuntu-latest

    container:
      image: maven:3.9.4  # Use a Maven image to avoid setup steps

    services:
      postgres_students:
        image: postgres:15.4
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: students
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres_programs:
        image: postgres:15.4
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: programs
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout v3
        uses: actions/checkout@v3

      - name: Build and Test Services
        run: |
          for service in config-service discovery-service gateway-service program-service student-service; do
            cd "$service"
            mvn clean install
            mvn test
            cd ..
          done

      - name: Run Integration Tests
        run: |
          # Run integration tests across microservices if applicable

  # Add more jobs for other types of tests, deployments, etc.
